import {
  NOMES_INSTRUMENTOS_AFERICAO,
  NOMES_VERIFICACOES_GERAIS_PREMONTAGEM,
  NOMES_VERIFICACAO_POSMONTAGEM,
} from '../constants/inspecaoMontagem';

// Hook para obter as constantes (sem dados de teste)
export const useInspecaoMontagem = () => {
  return {
    INSTRUMENTOS_AFERIÇÃO: NOMES_INSTRUMENTOS_AFERICAO,
    VERIFICACOES_GERAIS_PREMONTAGEM: NOMES_VERIFICACOES_GERAIS_PREMONTAGEM,
    VERIFICACAO_POSMONTAGEM: NOMES_VERIFICACAO_POSMONTAGEM,
  };
};
